version: '3.7'
services:
  server:
    build: .
    container_name: rbtm-drivers
    ports:
      - "10000:10000"
    #  - "3306:3306"
    restart: unless-stopped
    volumes:
      - "/dev/ximc/0000037A:/dev/ximc/0000037A"
      - "/dev/ximc/00000271:/dev/ximc/00000271"
      - "./logs:/var/log/supervisor"
    devices:
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/fw0:/dev/fw0"
      - "/dev/fw1:/dev/fw1"
    environment:
      - LD_LIBRARY_PATH=/var/www/drivers/package/libs/libusb/X64:/var/www/drivers/package/libs/libraw1394/X64:/var/www/drivers/package/api/X64
