version: '3.7'
services:
  tango-db:
    image: tangocs/mysql:9.2.2
    container_name: tango-db
    restart: unless-stopped
    ports:
     - "9999:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
  tango-cs:
    image: tangocs/tango-cs:9
    container_name: tango-cs
    restart: unless-stopped
    ports:
     - "10000:10000"
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=tango-db:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
      - tango-db
  drivers:
    build: .
    container_name: rbtm-drivers
    restart: unless-stopped
    volumes:
      - "/dev/ximc/0000037A:/dev/ximc/0000037A"
      - "/dev/ximc/00000271:/dev/ximc/00000271"
      - "./logs:/var/log/supervisor"
    devices:
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/fw0:/dev/fw0"
      - "/dev/fw1:/dev/fw1"
    environment:
      - LD_LIBRARY_PATH=/var/www/drivers/package/libs/libusb/X64:/var/www/drivers/package/libs/libraw1394/X64:/var/www/drivers/package/api/X64
      - TANGO_HOST=tango-cs:10000
    depends_on:
      - tango-cs
